using UnityEngine;

public class EngineHeatGenerator : MonoBehaviour
{
    public float heatIntensity = 100f; // Heat intensity generated by the engine
    public float heatRadius = 5f; // Radius within which heat is generated
    public LayerMask heatLayer; // Layer for heat detection

    private SphereCollider heatCollider;

    void Start()
    {
        // Initialize the sphere collider to simulate heat generation
        heatCollider = gameObject.AddComponent<SphereCollider>();
        heatCollider.isTrigger = true;
        heatCollider.radius = heatRadius;

        // Set the object's layer to the engine layer
        gameObject.layer = LayerMask.NameToLayer("Engine");
    }

    void OnDrawGizmos()
    {
        // Draw gizmos to visualize the heat radius in the editor
        Gizmos.color = Color.red;
        Gizmos.DrawWireSphere(transform.position, heatRadius);
    }

    public float GetHeatIntensity()
    {
        return heatIntensity;
    }

    public float GetHeatRadius()
    {
        return heatRadius;
    }

    void OnTriggerEnter(Collider other)
    {
        // You can add logic here to handle interactions with other objects
        // For example, you might want to check if the heat is detected by a heat-seeking missile
    }
}
